[tool.isort]
profile = "black"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]
addopts = "--cov=api --cov-report=term-missing"

[tool.pylint]
disable = ["fixme"]
[tool.pylint.MASTER]
ignore = ["tests"]
